### ISSUE TITLE
code error: where can I find file: deeplearning4ir.utils？

### ISSUE THREAD

**Issue by WonderMind** [AdeDZY/K-NRM#12]
Hi zhuyun,
I do not find deeplearning4ir.utils file in your project, can you help me to check it. Thank you very much!
https://github.com/AdeDZY/K-NRM/blob/fa5d60c38d894c3ef6cc7e580f60938773c3a8b3/knrm/data/generator.py#L235

**Comment by AdeDZY** [comment]
Hey, sorry about that!  A short solution is commenting out that line. It
only sets logging configurations, and will not affect the model.

**Comment by WonderMind** [comment]
Okay, thanks a lot.
