### ISSUE TITLE
求论文中的数据集

### ISSUE THREAD

**Issue by chizhu** [AdeDZY/K-NRM#18]
感谢你们的工作，对我很有帮助。可以给下你们论文中的数据集吗

**Comment by AdeDZY** [comment]
不好意思，这个数据集没有办法公开。不过我们所使用的Sogou Log与SogouT-16很相近，你可以联系下文的作者获得SogouT-16的数据集

SogouT-16: A New Web Corpus to Embrace IR Research

**Comment by chizhu** [comment]
好的，感谢您的回复！
