### ISSUE TITLE
can use the samples that their different score is 1?

### ISSUE THREAD

**Issue by bayou3** [AdeDZY/K-NRM#6]
Hello, 
I use Letor4 dataset, which owns three levels of judgement for query-docs, 2, 1, 0. Then the difference of scores between two samples are always 1, because I generate training or testing sample by considering "level-2 doc and level-1 doc" , "level-1 and level-0 doc", is it OK?

**Comment by AdeDZY** [comment]
It is okay that diff_score is always 1.
Diff_score could be 2 if you also consider pairs of level-2 doc and level 0 doc.

**Comment by bayou3** [comment]
Thank you so much for your reply!
